AWSTemplateFormatVersion: "2010-09-09"
Description: |
  AWS Cloudformation template to create base resources for Querypal AWS Amplify App
Parameters:
  pEnv:
    Description: The environment name
    Type: String
    Default: master
  pGitHubAccessToken:
    Description: Your github access token used to create webhook and read-only deploy key. Should be stored in SSM Parameter store
    Type: AWS::SSM::Parameter::Value<String>
  pQuerypalGitHubRepo:
    Description: Querypal GitHUb repository. Default is the OSS version. This might change if you decide customize Querypal
    Type: String
    Default: https://github.com/thealpha93/querypal.git
  pQuerypalAppName:
    Description: Querypal AWS Amplify App Name
    Type: String
    Default: querypal
Resources:
  AmplifyDevBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: !Ref pEnv
      AppId: !GetAtt QuerypalAmplifyApp.AppId
      EnableAutoBuild: yes

  QuerypalAmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Ref pQuerypalAppName
      Repository: !Ref pQuerypalGitHubRepo
      AccessToken: !Ref pGitHubAccessToken
      Description: Querypal - Web UI for Amazon Athena
      IAMServiceRole: !GetAtt AmplifyServiceRole.Arn
      BuildSpec: |
        version: 1
        backend:
          phases:
            build:
              commands:
                - '# Execute Amplify CLI with the helper script'
                - amplifyPush --simple
        frontend:
          phases:
            preBuild:
              commands:
                - yarn install
            build:
              commands:
                - yarn run build
          artifacts:
            baseDirectory: dist
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*

  AmplifyServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: "amplify-console-role"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:CreateStack
                  - cloudformation:CreateStackSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:DescribeStackSet
                  - cloudformation:DescribeStackSetOperation
                  - cloudformation:DescribeStacks
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:GetTemplate
                  - cloudformation:GetTemplateSummary
                  - cloudformation:UpdateStack
                  - cloudformation:UpdateStackSet
                  - cloudformation:ValidateTemplate
              - Resource: "*"
                Effect: Allow
                Action:
                  - iam:AttachRolePolicy
                  - iam:CreatePolicy
                  - iam:CreatePolicyVersion
                  - iam:CreateRole
                  - iam:CreateServiceLinkedRole
                  - iam:GetPolicy
                  - iam:GetPolicyVersion
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - iam:ListPolicies
                  - iam:ListPolicyVersions
                  - iam:ListRolePolicies
                  - iam:ListRoles
                  - iam:PassRole
                  - iam:PutGroupPolicy
                  - iam:PutRolePolicy
                  - iam:TagRole
                  - iam:UntagRole
                  - iam:UpdateAssumeRolePolicy
                  - iam:UpdateRole
                  - iam:UpdateRoleDescription
              - Resource: "*"
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Resource: "*"
                Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - s3:GetBucketPolicy
                  - s3:GetEncryptionConfiguration
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutBucketAcl
                  - s3:PutBucketPolicy
                  - s3:PutBucketVersioning
                  - s3:PutBucketWebsite
                  - s3:PutEncryptionConfiguration
                  - s3:PutObject
                  - s3:PutObjectAcl
              - Resource: "*"
                Effect: Allow
                Action:
                  - dynamodb:CreateTable
                  - dynamodb:DescribeTable
                  - dynamodb:UpdateTable
              - Resource: "*"
                Effect: Allow
                Action:
                  - cognito-identity:CreateIdentityPool
                  - cognito-identity:DescribeIdentity
                  - cognito-identity:DescribeIdentityPool
                  - cognito-identity:SetIdentityPoolRoles
                  - cognito-identity:UpdateIdentityPool
                  - cognito-idp:CreateGroup
                  - cognito-idp:CreateUserPool
                  - cognito-idp:CreateUserPoolClient
                  - cognito-idp:DescribeUserPool
                  - cognito-idp:UpdateUserPool
                  - cognito-idp:UpdateUserPoolClient
              - Resource: "*"
                Effect: Allow
                Action:
                  - codecommit:GitPull
                  - codecommit:GetRepository
                  - codecommit:GetRepositoryTriggers
                  - codecommit:PutRepositoryTriggers
              - Resource: "*"
                Effect: Allow
                Action:
                  - lambda:AddPermission
                  - lambda:CreateEventSourceMapping
                  - lambda:CreateFunction
                  - lambda:GetEventSourceMapping
                  - lambda:GetFunction
                  - lambda:GetFunctionConfiguration
                  - lambda:ListEventSourceMappings
                  - lambda:ListFunctions
                  - lambda:ListTags
                  - lambda:InvokeFunction
                  - lambda:TagResource
                  - lambda:UpdateEventSourceMapping
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
              - Resource: "*"
                Effect: Allow
                Action:
                  - amplify:CreateBackendEnvironment
                  - amplify:GetApp
                  - amplify:GetBackendEnvironment
                  - amplify:ListApps
                  - amplify:TagResource
                  - amplify:UntagResource
                  - amplify:UpdateApp
              - Resource: "*"
                Effect: Allow
                Action:
                  - appsync:CreateDataSource
                  - appsync:CreateGraphqlApi
                  - appsync:CreateResolver
                  - appsync:GetGraphqlApi
                  - appsync:GetSchemaCreationStatus
                  - appsync:StartSchemaCreation
                  - appsync:UpdateDataSource
                  - appsync:UpdateGraphqlApi
                  - appsync:UpdateResolver
  ######## SSM #########
  AmplifyAppIdSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /Querypal/Amplify/AppID
      Type: String
      Value: !GetAtt QuerypalAmplifyApp.AppId
      Description: Querypal Amplify App Id

Outputs:
  QuerypalAmplifyDomain:
    Value: !Sub 'https://${pEnv}.${QuerypalAmplifyApp.DefaultDomain}'
  QuerypalAmplifyAppId:
    Value: !GetAtt QuerypalAmplifyApp.AppId
